<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Parameter extends Model
{

    protected $table = 'parameters';

    protected $guarded = [];

    protected $casts = [
        'CMMaxNo' => 'integer',
        'CMMaxAmt' => 'integer',
        'Restruct_Percent' => 'decimal:4',
        'GetFromPrincipal' => 'boolean',
        'GetFromInterest' => 'boolean',
        'GetFromSavings' => 'boolean',
        'PromptAcctDtlYN' => 'boolean',
        'AutoCR_No' => 'integer',
        'AutoCV_No' => 'integer',
        'AutoJV_No' => 'integer',
        'AllowEditOR' => 'boolean',
        'AllowEditCV' => 'boolean',
        'AllowEditJV' => 'boolean',
        'MembershipFee' => 'decimal:4',
        'StartCollMemFee' => 'datetime',
        'MinBeneficiaries' => 'integer',
        'ShareCapitalAmt' => 'decimal:4',
        'ShareCapitalNo' => 'integer',
        'ChargePenalty' => 'boolean',
        'PenaltyCharging' => 'integer',
        'PenaltyChargeMode' => 'integer',
        'PenaltyRate' => 'decimal:4',
        'GracePeriod' => 'integer',
        'AnnualFee' => 'decimal:4',
        'MinNoOfCM' => 'integer',
        'AnnualCollDate' => 'datetime',
        'MaintainBalance' => 'decimal:4',
        'MaxLine' => 'integer',
        'MaxPage' => 'integer',
        'LnMaxLine' => 'integer',
        'LnMaxPage' => 'integer',
        'RoundOffAmort' => 'boolean',
        'TimeDepInt' => 'decimal:4',
        'NoDaysYr' => 'integer',
        'NoWksYr' => 'integer',
        'SysDate' => 'boolean',
        'IntBestPractice' => 'integer',
        'CollectRebateTag' => 'boolean',
        'Repost' => 'boolean',
        'PBookSkipLn' => 'integer',
        'PBookSkipLnNo' => 'integer',
        'MortuaryFundTag' => 'boolean',
        'UpfrontInterestTag' => 'boolean',
        'MinimumPenalty' => 'decimal:4',
        'IntOnSavingsMinBalance' => 'decimal:4',
        'PassBookTmplt' => 'integer',
        'TimeDepPostType' => 'integer',
        'TimeDepPostType2' => 'integer',
        'PassBookHdr1' => 'integer',
        'PassBookHdr2' => 'integer',
        'LedgerTmplt' => 'integer',
        'LedgerHdr' => 'integer',
        'LoanPassBookTmplt' => 'integer',
        'LoanPassBookHdr' => 'integer',
        'LoanLedgerTmplt' => 'integer',
        'LoanLedgerHdr' => 'integer',
        'CVTmplt' => 'integer',
        'ORTmplt' => 'integer',
        'JVTmplt' => 'integer',
        'ParValue' => 'decimal:4',
        'CMVariable' => 'boolean',
        'DisclosureStatementType' => 'integer',
        'UseLoanNo' => 'boolean',
        'CoMakerType' => 'boolean',
        'ReportSLType' => 'boolean',
        'LnPBookSkipLn' => 'integer',
        'LnPBookSkipLnNo' => 'integer',
        'LnMaxLineLedger' => 'integer',
        'LnMaxPageLedger' => 'integer',
        'MaxLineLedger' => 'integer',
        'MaxLoanAmountType' => 'integer',
        'MortBenOverDueLoans' => 'integer',
        'MortBenLengthMember' => 'integer',
        'MortBenMemberAge' => 'integer',
        'MortContOverDueLoans' => 'integer',
        'MortContLengthMember' => 'integer',
        'MortContMemberAge' => 'integer',
        'MortValueLengthMember' => 'integer',
        'MortValueMemberAge' => 'integer',
        'MaxTimeDepLine' => 'integer',
        'MaxTimeDepPage' => 'integer',
        'SkipLineTimeDep' => 'integer',
        'SkipLineTimeDepNo' => 'integer',
        'MaxTimeDepLedgerLine' => 'integer',
        'MaxTimeDepLedgerPage' => 'integer',
        'FixedDepAllotment' => 'decimal:4',
        'RefundAllotment' => 'decimal:4',
        'FixedDepCutOff' => 'decimal:4',
        'FixedDepValue' => 'decimal:4',
        'RefundValue' => 'decimal:4',
    ];
}
